settings: Avoid build error due to bad `ularge` overload
Since `ularge` is defined as `uint64_t`, which is `unsigned long` on
Linux, but `unsigned long long` on macOS, so we need to be careful
about not using `1ULL` in constants, otherwise the `format` function
does not match.

Compiler error:

```
../src/settings.cc:153:15: error: call of overloaded ‘format(settings&, renderer&, const char [23], long long unsigned int)’ is ambiguous
```

Fixes: #853